#!/bin/bash
echo "#!/bin/bash -e" > $1.tmp
if grep -q -e "--libc=klee" -e "%kleaver" $2; then
	echo 'echo "$0 SKIP"' >> $1.tmp
else
	echo "exec 6>&1" >> $1.tmp;
	echo "exec &>$1.log" >> $1.tmp;
	echo "not() { if \"\$@\"; then return 1; else return 0; fi }" >> $1.tmp;
	echo "set -x" >> $1.tmp;
	grep RUN: $2 | sed \
		-e "s,// RUN: ,,g" \
		-e "s,; RUN: ,,g" \
		-e "s,%llvmgxx,clang++ -emit-llvm,g" \
		-e "s,%llvmgcc,clang -emit-llvm,g" \
		-e "s,llvm-as,${LLVMAS},g" \
		-e "s,llvm-ld,${LLVMLD},g" \
		-e "s,../../../include,include,g" \
		-e "s,../../include,include,g" \
		-e "s,%p/../,test/,g" \
		-e "s,xxx,$1.dir,g" \
		-e "s,%s,$2,g" \
		-e "s,%t,$1,g" \
		-e "s,%t1,$1,g" \
		-e "s,%t2,$1.out,g" \
		-e "s,klee-last,$(dirname $1)/klee-last,g" \
		-e "s,%klee,build/bin/klee --klee-lib-dir=$(pwd)/build/lib,g" \
		-e "s,%ktest-tool,build/bin/ktest-tool,g" \
		>> $1.tmp;
	echo 'set +x' >> $1.tmp
	echo 'exec 1>&6' >> $1.tmp
	echo 'echo "$0 OK"' >> $1.tmp
	echo 'exit 0' >> $1.tmp
fi
chmod a+x $1.tmp;
mv $1.tmp $1
